# Generated by Django 2.1.5 on 2019-01-23 08:16

import backend.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=15)),
                ('currency', models.CharField(max_length=1)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=backend.company.models.generate_logo_upload_location)),
            ],
        ),
    ]
