# Generated by Django 2.1.5 on 2019-01-30 12:35

from django.db import migrations


def create_default_company(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    if len(Company.objects.all()) == 0:
        Company.objects.create(
            name='Your Company Name',
            email='company@email.com',
            address='Your Company Address',
            phone='+123123123',
            currency='$')


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_company),
    ]
