# Generated by Django 2.1.5 on 2019-02-03 15:37

import backend.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190130_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='small_logo',
            field=models.ImageField(null=True, upload_to=backend.company.models.generate_small_logo_upload_location),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to=backend.company.models.generate_logo_upload_location),
        ),
    ]
