# Generated by Django 2.1.5 on 2019-03-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
