# Generated by Django 2.1.5 on 2019-01-21 09:30

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=15)),
                ('business', models.TextField(max_length=128)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(501, 'ZIP Code must be more than 500'), django.core.validators.MaxValueValidator(99950, 'ZIP Code must be below 99951')])),
            ],
        ),
    ]
